In [2]:
import numpy as np
np.random.seed(0)

In [11]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))
x3

array([[[9, 1, 4, 6, 8],
        [2, 3, 0, 0, 6],
        [0, 6, 3, 3, 8],
        [8, 8, 2, 3, 2]],

       [[0, 8, 8, 3, 8],
        [2, 8, 4, 3, 0],
        [4, 3, 6, 9, 8],
        [0, 8, 5, 9, 0]],

       [[9, 6, 5, 3, 1],
        [8, 0, 4, 9, 6],
        [5, 7, 8, 8, 9],
        [2, 8, 6, 6, 9]]])

In [10]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)


x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [13]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x[:5]

array([0, 1, 2, 3, 4])

In [15]:
x[5:]

array([5, 6, 7, 8, 9])

In [16]:
x[::2]

array([0, 2, 4, 6, 8])

In [17]:
x2

array([[2, 7, 2, 9],
       [2, 3, 3, 2],
       [3, 4, 1, 2]])

In [18]:
x2[:2, :3]

array([[2, 7, 2],
       [2, 3, 3]])

In [19]:
print(x2)

[[2 7 2 9]
 [2 3 3 2]
 [3 4 1 2]]


In [21]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[2 7]
 [2 3]]


In [22]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  7]
 [ 2  3]]


In [23]:
print(x2)

[[99  7  2  9]
 [ 2  3  3  2]
 [ 3  4  1  2]]


In [35]:
a = np.arange(3)
b = np.arange(3)
b.reshape(-1, 1)

print(a)
print(b)

[0 1 2]
[0 1 2]


In [38]:
b.reshape(-1)
b

array([0, 1, 2])

In [40]:
a = np.arange(3).reshape(3,1)
b = np.arange(3)
print(a)
print(b)


[[0]
 [1]
 [2]]
[0 1 2]


In [42]:
print(a.shape)
print(b.shape)

(3, 1)
(3,)


In [43]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [48]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                                 'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [47]:
print(data)

[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]


In [50]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [53]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [54]:
data.index

RangeIndex(start=0, stop=4, step=1)